// Extracts the full, fragment-inlined GraphQL operation texts that the Relay
// compiler produced (each generated operation file's `params.text`) into
// lib/graphql/queries.js, so the hand-rolled client sends exactly the queries
// the Relay client did. Run with: node scripts/extract-queries.js
const fs = require("fs");
const path = require("path");

const libRoot = path.join(__dirname, "..", "lib");
const results = {};
const skipped = [];

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full);
    } else if (path.basename(dir) === "__generated__" && entry.name.endsWith(".graphql.js")) {
      let node;
      try {
        node = require(full);
      } catch (e) {
        skipped.push([entry.name, "require failed: " + e.message]);
        continue;
      }
      const params = node && node.params;
      if (!params || (params.operationKind !== "query" && params.operationKind !== "mutation")) {
        continue;
      }
      if (typeof params.text === "string" && params.text.length > 0) {
        results[params.name] = params.text;
      } else {
        skipped.push([params.name, "no params.text (persisted query?)"]);
      }
    }
  }
}

walk(libRoot);

const names = Object.keys(results).sort();
let out =
  "/** @babel */\n\n" +
  "// GENERATED by scripts/extract-queries.js — do not edit by hand.\n" +
  "// Full GraphQL operation texts (every fragment inlined) taken from the Relay\n" +
  "// compiler output, so the hand-rolled client sends the same queries Relay did.\n\n";
for (const name of names) {
  out += `export const ${name} = ${JSON.stringify(results[name])};\n\n`;
}

fs.mkdirSync(path.join(libRoot, "graphql"), { recursive: true });
fs.writeFileSync(path.join(libRoot, "graphql", "queries.js"), out);

console.log(`Extracted ${names.length} operations into lib/graphql/queries.js:`);
console.log("  " + names.join("\n  "));
if (skipped.length) {
  console.log(`\nSkipped ${skipped.length}:`);
  for (const [name, reason] of skipped) console.log(`  ${name}: ${reason}`);
}
